# For more information, please refer to https://aka.ms/vscode-docker-python
FROM arm32v6/python:3-alpine

# Install pip requirements
ADD requirements.txt .
RUN apk add --no-cache --virtual build-deps gcc musl-dev && \
    python -m pip install -r requirements.txt && \
    apk del build-deps
