version: '3.4'

services:
  sensors:
    image: sensors
    build:
      context: .
      dockerfile: Dockerfile.arm32v6
    ports:
      - 80:5000
    # # Preferably this should be used over privileged but it's not working
    # devices:
    #   - /dev/gpiomem
    #   - /dev/gpiomem:/dev/gpiomem
    privileged: true
